<?php 

class PostTableSeeder extends Seeder {

    public function run()
    {
        $post = new Post();
        $post->title = 'My First Blog Post';
        $post->categories = 'Sample Post';
        $post->author = User::first()->first_name . ' ' . User::first()->last_name;
        $post->user_id = User::first()->id;
        $post->summary = "This is just a short summary of a blog post. It can contain 200 characters before it’s too long. I'm just typing to get as close to the limit as I possibly can. Hodor. Hodor. Hodor. Hodor. Hodor.";
        $post->body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae neque bibendum, varius lacus eu, porttitor tellus. Fusce efficitur, felis a rhoncus sodales, massa purus viverra quam, non bibendum enim nunc sed nisi. Cras venenatis, dui eget porttitor maximus, urna dolor sodales ante, aliquam varius diam metus sed tellus. Etiam quis ultricies ante. Aliquam auctor diam in facilisis convallis. Integer lorem tortor, hendrerit at odio id, efficitur pharetra ante. Ut leo justo, tincidunt elementum nunc vitae, iaculis vulputate mi. Praesent accumsan odio dapibus turpis tincidunt efficitur. Donec vitae auctor ante. Praesent luctus, magna ac volutpat feugiat, nibh arcu commodo dui, quis ornare eros arcu id erat.

Etiam porta augue justo, non tempor est ornare sit amet. Etiam eget venenatis ex. In quis elit id diam tincidunt tincidunt a in felis. Suspendisse fermentum pretium justo, ut eleifend felis pulvinar nec. Aenean non sapien vel ligula viverra mollis. Pellentesque varius leo eget mauris suscipit ullamcorper. Cras eget ligula ac turpis pretium hendrerit a sit amet magna. Cras sapien nunc, vehicula ut finibus ac, laoreet quis diam. Donec ac magna eu mi varius imperdiet ac euismod tellus. Aliquam erat volutpat. Vivamus lobortis vel nunc eget auctor.

Cras congue diam diam, nec tempor turpis blandit nec. Quisque tortor enim, dapibus non purus ut, semper finibus elit. Nullam feugiat quis urna ut facilisis. Sed vulputate faucibus tellus et pretium. Quisque eu lacus metus. Nam dictum, turpis et pulvinar tincidunt, enim arcu posuere augue, non fringilla orci tellus quis magna. Etiam commodo lectus vehicula sapien pharetra, auctor tempor urna malesuada. Morbi at consequat leo, ut laoreet magna. Aliquam nisi dolor, malesuada a egestas eu, interdum quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed semper tristique neque eget tincidunt. Nullam vulputate, tellus eu ultricies aliquam, neque sem maximus urna, eu vehicula odio neque id est. Nam ante magna, volutpat a laoreet et, malesuada scelerisque eros. Vivamus laoreet dolor lorem, sit amet imperdiet sem venenatis egestas.

Integer dignissim nec risus eu venenatis. Morbi aliquet ultrices quam a posuere. Etiam tempor euismod sagittis. Donec sollicitudin convallis nisl et sagittis. Ut eu justo pharetra, gravida nibh vitae, consequat tellus. Fusce aliquam dictum sodales. Donec sit amet nisi ut leo malesuada pretium. Proin et feugiat magna, at pharetra lorem. Sed fermentum eu ex ut vehicula. Donec scelerisque et nisi eu vestibulum. Morbi convallis tincidunt posuere. Integer porta urna fermentum urna ullamcorper, vel ullamcorper quam sagittis. Maecenas bibendum faucibus elit vel rhoncus. Nulla arcu tortor, mollis placerat nunc vel, feugiat mollis tellus. Duis ultrices ante libero, vitae varius urna elementum vel. In eleifend lacus sit amet purus condimentum, vitae efficitur ipsum consectetur.

Aenean aliquet velit est, vel laoreet nunc mollis a. Proin at magna nec justo auctor ullamcorper vel a libero. In vel lorem sit amet odio tempus suscipit ac at nibh. Nunc dapibus viverra metus quis gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus venenatis tellus enim, varius facilisis risus viverra sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum cursus, dolor feugiat vulputate pretium, diam tortor ornare ante, sed pellentesque enim diam vitae nulla. Etiam ac arcu posuere, malesuada turpis sit amet, congue justo. Curabitur in neque dictum, sagittis turpis sed, malesuada turpis. Aenean id cursus urna.

Sed leo nulla, rhoncus in lorem eget, viverra luctus nisi. Nam consequat in arcu eget feugiat. Maecenas a accumsan tortor, eu accumsan orci. Nam vel eros et dui pharetra vestibulum. Aenean leo elit, commodo a velit quis, rhoncus accumsan leo. Donec mattis lectus metus, a tempor orci convallis non. Proin consequat aliquet tellus sed congue. Suspendisse maximus porttitor pulvinar. Etiam pretium imperdiet mi, eleifend sollicitudin orci tincidunt non. Curabitur sodales vitae libero rhoncus euismod. Sed mattis eros consectetur dolor iaculis, a tempor enim cursus. Suspendisse molestie ut lorem sit amet imperdiet. Duis ut elit felis. Phasellus sit amet placerat ipsum. Duis at nibh sed metus pellentesque feugiat sit amet sit amet leo.

Cras tortor neque, commodo et ligula a, ultricies varius mi. Nulla feugiat tincidunt hendrerit. Sed efficitur feugiat erat at rutrum. Fusce vulputate tempus tellus auctor tincidunt. Donec efficitur congue cursus. Donec sed metus neque. Nullam orci nunc, ultrices a diam ac, aliquam blandit lorem.

Nunc mollis in mauris sit amet eleifend. Praesent id urna et nulla tincidunt tempus vel eu tellus. Vestibulum mi velit, mollis id ullamcorper et, eleifend quis nulla. Quisque vel tempor lorem, sit amet posuere nisl. Phasellus non pellentesque erat, eleifend elementum nisi. Morbi in quam commodo, accumsan libero quis, iaculis mauris. Donec tincidunt aliquam lorem. Ut varius lectus sit amet hendrerit rhoncus. Sed egestas a tellus non venenatis.

Aliquam et lorem quam. Sed sit amet convallis erat. Quisque vel justo nulla. Sed luctus vestibulum dui sodales dapibus. Nullam iaculis id neque id ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec imperdiet ex ac laoreet viverra. Etiam mollis eu ex ut laoreet. Mauris vitae sem tincidunt, feugiat felis nec, malesuada lectus. Suspendisse potenti.

Etiam blandit eros et lorem gravida, id laoreet tortor rutrum. Nullam ut luctus tortor. Nunc non turpis ullamcorper, placerat est a, vehicula lorem. Integer quis eros et sapien interdum sollicitudin vitae eu nisi. Nulla magna turpis, sagittis at velit a, consectetur tristique mi. Pellentesque ut mattis augue, quis ullamcorper purus. Vivamus vitae molestie justo. Proin ut tellus quis elit pretium malesuada quis ac nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris facilisis sed nisi non porta.';
        $post->image = 'img/postImg/6z707-stock19.jpg';
        $post->save();

        $post = new Post();
        $post->title = 'My Second Blog Post';
        $post->categories = 'Sample Post';
        $post->author = User::first()->first_name . ' ' . User::first()->last_name;
        $post->user_id = User::first()->id;
        $post->summary = "I'm really just writing a bunch of words. I know this is supposed to be a 'real' post, but this is not going to be a 'real' summary. I'm reaching the character limit, so I'll go ahead and stop here.";
        $post->body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae neque bibendum, varius lacus eu, porttitor tellus. Fusce efficitur, felis a rhoncus sodales, massa purus viverra quam, non bibendum enim nunc sed nisi. Cras venenatis, dui eget porttitor maximus, urna dolor sodales ante, aliquam varius diam metus sed tellus. Etiam quis ultricies ante. Aliquam auctor diam in facilisis convallis. Integer lorem tortor, hendrerit at odio id, efficitur pharetra ante. Ut leo justo, tincidunt elementum nunc vitae, iaculis vulputate mi. Praesent accumsan odio dapibus turpis tincidunt efficitur. Donec vitae auctor ante. Praesent luctus, magna ac volutpat feugiat, nibh arcu commodo dui, quis ornare eros arcu id erat.

Etiam porta augue justo, non tempor est ornare sit amet. Etiam eget venenatis ex. In quis elit id diam tincidunt tincidunt a in felis. Suspendisse fermentum pretium justo, ut eleifend felis pulvinar nec. Aenean non sapien vel ligula viverra mollis. Pellentesque varius leo eget mauris suscipit ullamcorper. Cras eget ligula ac turpis pretium hendrerit a sit amet magna. Cras sapien nunc, vehicula ut finibus ac, laoreet quis diam. Donec ac magna eu mi varius imperdiet ac euismod tellus. Aliquam erat volutpat. Vivamus lobortis vel nunc eget auctor.

Cras congue diam diam, nec tempor turpis blandit nec. Quisque tortor enim, dapibus non purus ut, semper finibus elit. Nullam feugiat quis urna ut facilisis. Sed vulputate faucibus tellus et pretium. Quisque eu lacus metus. Nam dictum, turpis et pulvinar tincidunt, enim arcu posuere augue, non fringilla orci tellus quis magna. Etiam commodo lectus vehicula sapien pharetra, auctor tempor urna malesuada. Morbi at consequat leo, ut laoreet magna. Aliquam nisi dolor, malesuada a egestas eu, interdum quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed semper tristique neque eget tincidunt. Nullam vulputate, tellus eu ultricies aliquam, neque sem maximus urna, eu vehicula odio neque id est. Nam ante magna, volutpat a laoreet et, malesuada scelerisque eros. Vivamus laoreet dolor lorem, sit amet imperdiet sem venenatis egestas.

Integer dignissim nec risus eu venenatis. Morbi aliquet ultrices quam a posuere. Etiam tempor euismod sagittis. Donec sollicitudin convallis nisl et sagittis. Ut eu justo pharetra, gravida nibh vitae, consequat tellus. Fusce aliquam dictum sodales. Donec sit amet nisi ut leo malesuada pretium. Proin et feugiat magna, at pharetra lorem. Sed fermentum eu ex ut vehicula. Donec scelerisque et nisi eu vestibulum. Morbi convallis tincidunt posuere. Integer porta urna fermentum urna ullamcorper, vel ullamcorper quam sagittis. Maecenas bibendum faucibus elit vel rhoncus. Nulla arcu tortor, mollis placerat nunc vel, feugiat mollis tellus. Duis ultrices ante libero, vitae varius urna elementum vel. In eleifend lacus sit amet purus condimentum, vitae efficitur ipsum consectetur.

Aenean aliquet velit est, vel laoreet nunc mollis a. Proin at magna nec justo auctor ullamcorper vel a libero. In vel lorem sit amet odio tempus suscipit ac at nibh. Nunc dapibus viverra metus quis gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus venenatis tellus enim, varius facilisis risus viverra sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum cursus, dolor feugiat vulputate pretium, diam tortor ornare ante, sed pellentesque enim diam vitae nulla. Etiam ac arcu posuere, malesuada turpis sit amet, congue justo. Curabitur in neque dictum, sagittis turpis sed, malesuada turpis. Aenean id cursus urna.

Sed leo nulla, rhoncus in lorem eget, viverra luctus nisi. Nam consequat in arcu eget feugiat. Maecenas a accumsan tortor, eu accumsan orci. Nam vel eros et dui pharetra vestibulum. Aenean leo elit, commodo a velit quis, rhoncus accumsan leo. Donec mattis lectus metus, a tempor orci convallis non. Proin consequat aliquet tellus sed congue. Suspendisse maximus porttitor pulvinar. Etiam pretium imperdiet mi, eleifend sollicitudin orci tincidunt non. Curabitur sodales vitae libero rhoncus euismod. Sed mattis eros consectetur dolor iaculis, a tempor enim cursus. Suspendisse molestie ut lorem sit amet imperdiet. Duis ut elit felis. Phasellus sit amet placerat ipsum. Duis at nibh sed metus pellentesque feugiat sit amet sit amet leo.

Cras tortor neque, commodo et ligula a, ultricies varius mi. Nulla feugiat tincidunt hendrerit. Sed efficitur feugiat erat at rutrum. Fusce vulputate tempus tellus auctor tincidunt. Donec efficitur congue cursus. Donec sed metus neque. Nullam orci nunc, ultrices a diam ac, aliquam blandit lorem.

Nunc mollis in mauris sit amet eleifend. Praesent id urna et nulla tincidunt tempus vel eu tellus. Vestibulum mi velit, mollis id ullamcorper et, eleifend quis nulla. Quisque vel tempor lorem, sit amet posuere nisl. Phasellus non pellentesque erat, eleifend elementum nisi. Morbi in quam commodo, accumsan libero quis, iaculis mauris. Donec tincidunt aliquam lorem. Ut varius lectus sit amet hendrerit rhoncus. Sed egestas a tellus non venenatis.

Aliquam et lorem quam. Sed sit amet convallis erat. Quisque vel justo nulla. Sed luctus vestibulum dui sodales dapibus. Nullam iaculis id neque id ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec imperdiet ex ac laoreet viverra. Etiam mollis eu ex ut laoreet. Mauris vitae sem tincidunt, feugiat felis nec, malesuada lectus. Suspendisse potenti.

Etiam blandit eros et lorem gravida, id laoreet tortor rutrum. Nullam ut luctus tortor. Nunc non turpis ullamcorper, placerat est a, vehicula lorem. Integer quis eros et sapien interdum sollicitudin vitae eu nisi. Nulla magna turpis, sagittis at velit a, consectetur tristique mi. Pellentesque ut mattis augue, quis ullamcorper purus. Vivamus vitae molestie justo. Proin ut tellus quis elit pretium malesuada quis ac nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris facilisis sed nisi non porta.';
        $post->image = 'img/postImg/8urm3-stock7.jpg';
        $post->save();

        $post = new Post();
        $post->title = 'My Third Blog Post';
        $post->categories = 'Sample Post';
        $post->author = User::first()->first_name . ' ' . User::first()->last_name;
        $post->user_id = User::first()->id;
        $post->summary = "Here we go again with the summary...I haven't written the post yet, so how could I possibly summarize it? That's right, I can't. That's why I'm writing this silly text...errrrr...WAS writing it.";
        $post->body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vitae neque bibendum, varius lacus eu, porttitor tellus. Fusce efficitur, felis a rhoncus sodales, massa purus viverra quam, non bibendum enim nunc sed nisi. Cras venenatis, dui eget porttitor maximus, urna dolor sodales ante, aliquam varius diam metus sed tellus. Etiam quis ultricies ante. Aliquam auctor diam in facilisis convallis. Integer lorem tortor, hendrerit at odio id, efficitur pharetra ante. Ut leo justo, tincidunt elementum nunc vitae, iaculis vulputate mi. Praesent accumsan odio dapibus turpis tincidunt efficitur. Donec vitae auctor ante. Praesent luctus, magna ac volutpat feugiat, nibh arcu commodo dui, quis ornare eros arcu id erat.

Etiam porta augue justo, non tempor est ornare sit amet. Etiam eget venenatis ex. In quis elit id diam tincidunt tincidunt a in felis. Suspendisse fermentum pretium justo, ut eleifend felis pulvinar nec. Aenean non sapien vel ligula viverra mollis. Pellentesque varius leo eget mauris suscipit ullamcorper. Cras eget ligula ac turpis pretium hendrerit a sit amet magna. Cras sapien nunc, vehicula ut finibus ac, laoreet quis diam. Donec ac magna eu mi varius imperdiet ac euismod tellus. Aliquam erat volutpat. Vivamus lobortis vel nunc eget auctor.

Cras congue diam diam, nec tempor turpis blandit nec. Quisque tortor enim, dapibus non purus ut, semper finibus elit. Nullam feugiat quis urna ut facilisis. Sed vulputate faucibus tellus et pretium. Quisque eu lacus metus. Nam dictum, turpis et pulvinar tincidunt, enim arcu posuere augue, non fringilla orci tellus quis magna. Etiam commodo lectus vehicula sapien pharetra, auctor tempor urna malesuada. Morbi at consequat leo, ut laoreet magna. Aliquam nisi dolor, malesuada a egestas eu, interdum quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed semper tristique neque eget tincidunt. Nullam vulputate, tellus eu ultricies aliquam, neque sem maximus urna, eu vehicula odio neque id est. Nam ante magna, volutpat a laoreet et, malesuada scelerisque eros. Vivamus laoreet dolor lorem, sit amet imperdiet sem venenatis egestas.

Integer dignissim nec risus eu venenatis. Morbi aliquet ultrices quam a posuere. Etiam tempor euismod sagittis. Donec sollicitudin convallis nisl et sagittis. Ut eu justo pharetra, gravida nibh vitae, consequat tellus. Fusce aliquam dictum sodales. Donec sit amet nisi ut leo malesuada pretium. Proin et feugiat magna, at pharetra lorem. Sed fermentum eu ex ut vehicula. Donec scelerisque et nisi eu vestibulum. Morbi convallis tincidunt posuere. Integer porta urna fermentum urna ullamcorper, vel ullamcorper quam sagittis. Maecenas bibendum faucibus elit vel rhoncus. Nulla arcu tortor, mollis placerat nunc vel, feugiat mollis tellus. Duis ultrices ante libero, vitae varius urna elementum vel. In eleifend lacus sit amet purus condimentum, vitae efficitur ipsum consectetur.

Aenean aliquet velit est, vel laoreet nunc mollis a. Proin at magna nec justo auctor ullamcorper vel a libero. In vel lorem sit amet odio tempus suscipit ac at nibh. Nunc dapibus viverra metus quis gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus venenatis tellus enim, varius facilisis risus viverra sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum cursus, dolor feugiat vulputate pretium, diam tortor ornare ante, sed pellentesque enim diam vitae nulla. Etiam ac arcu posuere, malesuada turpis sit amet, congue justo. Curabitur in neque dictum, sagittis turpis sed, malesuada turpis. Aenean id cursus urna.

Sed leo nulla, rhoncus in lorem eget, viverra luctus nisi. Nam consequat in arcu eget feugiat. Maecenas a accumsan tortor, eu accumsan orci. Nam vel eros et dui pharetra vestibulum. Aenean leo elit, commodo a velit quis, rhoncus accumsan leo. Donec mattis lectus metus, a tempor orci convallis non. Proin consequat aliquet tellus sed congue. Suspendisse maximus porttitor pulvinar. Etiam pretium imperdiet mi, eleifend sollicitudin orci tincidunt non. Curabitur sodales vitae libero rhoncus euismod. Sed mattis eros consectetur dolor iaculis, a tempor enim cursus. Suspendisse molestie ut lorem sit amet imperdiet. Duis ut elit felis. Phasellus sit amet placerat ipsum. Duis at nibh sed metus pellentesque feugiat sit amet sit amet leo.

Cras tortor neque, commodo et ligula a, ultricies varius mi. Nulla feugiat tincidunt hendrerit. Sed efficitur feugiat erat at rutrum. Fusce vulputate tempus tellus auctor tincidunt. Donec efficitur congue cursus. Donec sed metus neque. Nullam orci nunc, ultrices a diam ac, aliquam blandit lorem.

Nunc mollis in mauris sit amet eleifend. Praesent id urna et nulla tincidunt tempus vel eu tellus. Vestibulum mi velit, mollis id ullamcorper et, eleifend quis nulla. Quisque vel tempor lorem, sit amet posuere nisl. Phasellus non pellentesque erat, eleifend elementum nisi. Morbi in quam commodo, accumsan libero quis, iaculis mauris. Donec tincidunt aliquam lorem. Ut varius lectus sit amet hendrerit rhoncus. Sed egestas a tellus non venenatis.

Aliquam et lorem quam. Sed sit amet convallis erat. Quisque vel justo nulla. Sed luctus vestibulum dui sodales dapibus. Nullam iaculis id neque id ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec imperdiet ex ac laoreet viverra. Etiam mollis eu ex ut laoreet. Mauris vitae sem tincidunt, feugiat felis nec, malesuada lectus. Suspendisse potenti.

Etiam blandit eros et lorem gravida, id laoreet tortor rutrum. Nullam ut luctus tortor. Nunc non turpis ullamcorper, placerat est a, vehicula lorem. Integer quis eros et sapien interdum sollicitudin vitae eu nisi. Nulla magna turpis, sagittis at velit a, consectetur tristique mi. Pellentesque ut mattis augue, quis ullamcorper purus. Vivamus vitae molestie justo. Proin ut tellus quis elit pretium malesuada quis ac nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris facilisis sed nisi non porta.';
        $post->image = 'img/postImg/bc0fu-stock6.jpg';
        $post->save();
    }
}

?>